/* Autogenerated by onion assets */
#ifndef __ASSETS_H__ASSETS_H
#define __ASSETS_H__ASSETS_H
# ifdef __cplusplus
extern "C"{
# endif
#include <onion/types.h>
void index_html(onion_dict *context, onion_response *res);
// New data will be inserted over this line. DO NOT MODIFY (SPECIALLY THIS LINE).
# ifdef __cplusplus 
} // extern "C"
# endif 
#endif
